name: Jesper Kjelgaard
url: 'http://thejspr.com'
description: 'Blog and portfolio of Jesper Kjeldgaard (thejspr)'
pygments: true
permalink: 'blog/:title'
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock']
