name: Jesper Kjelgaard
url: 'https://thejspr.com'
description: 'Blog and portfolio of Jesper Kjeldgaard'
permalink: 'blog/:title'
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']
gems:
  - jekyll-sitemap
